// Ícones usando @iconify/react
// Formato: "conjunto:nome-do-icone"
export const PRODUCT_ICONS: Record<string, string> = {
  // Laticínios e Derivados
  'leite': 'fluent-emoji:glass-of-milk',
  'iogurte': 'fluent-emoji:cup-with-straw',
  'yogurt': 'fluent-emoji:cup-with-straw',
  'queijo': 'fluent-emoji:cheese-wedge',
  'manteiga': 'fluent-emoji:butter',
  'requeijão': 'fluent-emoji:butter',
  'requeijao': 'fluent-emoji:butter',
  'cream cheese': 'fluent-emoji:cheese-wedge',
  'nata': 'fluent-emoji:glass-of-milk',
  'coalhada': 'fluent-emoji:cup-with-straw',
  'ricota': 'fluent-emoji:cheese-wedge',
  'creme de leite': 'fluent-emoji:glass-of-milk',

  // Padaria
  'pão': 'fluent-emoji:bread',
  'pao': 'fluent-emoji:bread',
  'torrada': 'fluent-emoji:bread',
  'bolo': 'fluent-emoji:birthday-cake',
  'croissant': 'fluent-emoji:croissant',
  'bisnaga': 'fluent-emoji:bread',
  'baguete': 'fluent-emoji:baguette-bread',
  'pão francês': 'fluent-emoji:baguette-bread',
  'pao frances': 'fluent-emoji:baguette-bread',
  'pão de forma': 'fluent-emoji:bread',
  'pao de forma': 'fluent-emoji:bread',
  'rosca': 'fluent-emoji:bagel',
  'sonho': 'fluent-emoji:doughnut',
  'donut': 'fluent-emoji:doughnut',
  'rosquinha': 'fluent-emoji:doughnut',
  'cupcake': 'fluent-emoji:cupcake',
  'torta': 'fluent-emoji:pie',
  'pretzel': 'fluent-emoji:pretzel',
  'bagel': 'fluent-emoji:bagel',

  // Carnes e Proteínas
  'carne': 'fluent-emoji:cut-of-meat',
  'bife': 'fluent-emoji:cut-of-meat',
  'filé': 'fluent-emoji:cut-of-meat',
  'file': 'fluent-emoji:cut-of-meat',
  'picanha': 'fluent-emoji:cut-of-meat',
  'costela': 'fluent-emoji:cut-of-meat',
  'alcatra': 'fluent-emoji:cut-of-meat',
  'frango': 'fluent-emoji:poultry-leg',
  'peito de frango': 'fluent-emoji:poultry-leg',
  'coxa de frango': 'fluent-emoji:poultry-leg',
  'asa de frango': 'fluent-emoji:poultry-leg',
  'peixe': 'fluent-emoji:fish',
  'salmão': 'fluent-emoji:fish',
  'salmao': 'fluent-emoji:fish',
  'tilápia': 'fluent-emoji:fish',
  'tilapia': 'fluent-emoji:fish',
  'atum': 'fluent-emoji:fish',
  'bacalhau': 'fluent-emoji:fish',
  'camarão': 'fluent-emoji:shrimp',
  'camarao': 'fluent-emoji:shrimp',
  'bacon': 'fluent-emoji:bacon',
  'salsicha': 'fluent-emoji:hot-dog',
  'linguiça': 'fluent-emoji:hot-dog',
  'linguica': 'fluent-emoji:hot-dog',
  'salame': 'fluent-emoji:bacon',
  'presunto': 'fluent-emoji:bacon',
  'mortadela': 'fluent-emoji:bacon',
  'calabresa': 'fluent-emoji:hot-dog',

  // Frutas
  'maçã': 'fluent-emoji:red-apple',
  'maca': 'fluent-emoji:red-apple',
  'banana': 'fluent-emoji:banana',
  'laranja': 'fluent-emoji:tangerine',
  'mexerica': 'fluent-emoji:tangerine',
  'tangerina': 'fluent-emoji:tangerine',
  'bergamota': 'fluent-emoji:tangerine',
  'uva': 'fluent-emoji:grapes',
  'morango': 'fluent-emoji:strawberry',
  'melancia': 'fluent-emoji:watermelon',
  'abacaxi': 'fluent-emoji:pineapple',
  'limão': 'fluent-emoji:lemon',
  'limao': 'fluent-emoji:lemon',
  'manga': 'fluent-emoji:mango',
  'pera': 'fluent-emoji:pear',
  'pêssego': 'fluent-emoji:peach',
  'pessego': 'fluent-emoji:peach',
  'cereja': 'fluent-emoji:cherries',
  'kiwi': 'fluent-emoji:kiwi-fruit',
  'melão': 'fluent-emoji:melon',
  'melao': 'fluent-emoji:melon',
  'mamão': 'fluent-emoji:melon',
  'mamao': 'fluent-emoji:melon',
  'coco': 'fluent-emoji:coconut',
  'abacate': 'fluent-emoji:avocado',
  'blueberry': 'fluent-emoji:blueberries',
  'mirtilo': 'fluent-emoji:blueberries',
  'framboesa': 'fluent-emoji:strawberry',
  'amora': 'fluent-emoji:blueberries',
  'goiaba': 'fluent-emoji:peach',
  'maracujá': 'fluent-emoji:melon',
  'maracuja': 'fluent-emoji:melon',
  'caqui': 'fluent-emoji:tangerine',
  'figo': 'fluent-emoji:pear',
  'ameixa': 'fluent-emoji:peach',

  // Vegetais e Verduras
  'tomate': 'fluent-emoji:tomato',
  'alface': 'fluent-emoji:leafy-green',
  'cenoura': 'fluent-emoji:carrot',
  'batata': 'fluent-emoji:potato',
  'batata inglesa': 'fluent-emoji:potato',
  'batata doce': 'fluent-emoji:potato',
  'mandioca': 'fluent-emoji:potato',
  'aipim': 'fluent-emoji:potato',
  'macaxeira': 'fluent-emoji:potato',
  'cebola': 'fluent-emoji:onion',
  'alho': 'fluent-emoji:garlic',
  'brócolis': 'fluent-emoji:broccoli',
  'brocolis': 'fluent-emoji:broccoli',
  'berinjela': 'fluent-emoji:eggplant',
  'pimentão': 'fluent-emoji:bell-pepper',
  'pimentao': 'fluent-emoji:bell-pepper',
  'pepino': 'fluent-emoji:cucumber',
  'milho': 'fluent-emoji:ear-of-corn',
  'cogumelo': 'fluent-emoji:mushroom',
  'champignon': 'fluent-emoji:mushroom',
  'pimenta': 'fluent-emoji:hot-pepper',
  'abóbora': 'fluent-emoji:pumpkin',
  'abobora': 'fluent-emoji:pumpkin',
  'moranga': 'fluent-emoji:pumpkin',
  'abobrinha': 'fluent-emoji:cucumber',
  'couve': 'fluent-emoji:leafy-green',
  'espinafre': 'fluent-emoji:leafy-green',
  'repolho': 'fluent-emoji:leafy-green',
  'couve-flor': 'fluent-emoji:broccoli',
  'couve flor': 'fluent-emoji:broccoli',
  'beterraba': 'fluent-emoji:onion',
  'rabanete': 'fluent-emoji:onion',
  'nabo': 'fluent-emoji:onion',
  'vagem': 'fluent-emoji:leafy-green',
  'quiabo': 'fluent-emoji:cucumber',
  'jiló': 'fluent-emoji:eggplant',
  'jilo': 'fluent-emoji:eggplant',
  'chuchu': 'fluent-emoji:cucumber',
  'agrião': 'fluent-emoji:leafy-green',
  'agriao': 'fluent-emoji:leafy-green',
  'rúcula': 'fluent-emoji:leafy-green',
  'rucula': 'fluent-emoji:leafy-green',
  'chicória': 'fluent-emoji:leafy-green',
  'chicoria': 'fluent-emoji:leafy-green',

  // Grãos, Massas e Cereais
  'arroz': 'fluent-emoji:cooked-rice',
  'feijão': 'fluent-emoji:beans',
  'feijao': 'fluent-emoji:beans',
  'macarrão': 'fluent-emoji:spaghetti',
  'macarrao': 'fluent-emoji:spaghetti',
  'espaguete': 'fluent-emoji:spaghetti',
  'massa': 'fluent-emoji:spaghetti',
  'penne': 'fluent-emoji:spaghetti',
  'fusilli': 'fluent-emoji:spaghetti',
  'talharim': 'fluent-emoji:spaghetti',
  'lasanha': 'fluent-emoji:spaghetti',
  'farinha': 'fluent-emoji:salt',
  'farinha de trigo': 'fluent-emoji:salt',
  'farinha de milho': 'fluent-emoji:salt',
  'fubá': 'fluent-emoji:salt',
  'fuba': 'fluent-emoji:salt',
  'aveia': 'fluent-emoji:cooked-rice',
  'granola': 'fluent-emoji:cooked-rice',
  'lentilha': 'fluent-emoji:beans',
  'grão de bico': 'fluent-emoji:beans',
  'grao de bico': 'fluent-emoji:beans',
  'ervilha': 'fluent-emoji:beans',
  'quinoa': 'fluent-emoji:cooked-rice',
  'chia': 'fluent-emoji:cooked-rice',
  'linhaça': 'fluent-emoji:cooked-rice',
  'linhaca': 'fluent-emoji:cooked-rice',

  // Bebidas
  'café': 'fluent-emoji:hot-beverage',
  'cafe': 'fluent-emoji:hot-beverage',
  'chá': 'fluent-emoji:teacup-without-handle',
  'cha': 'fluent-emoji:teacup-without-handle',
  'suco': 'fluent-emoji:beverage-box',
  'refrigerante': 'fluent-emoji:cup-with-straw',
  'refri': 'fluent-emoji:cup-with-straw',
  'coca': 'fluent-emoji:cup-with-straw',
  'pepsi': 'fluent-emoji:cup-with-straw',
  'guaraná': 'fluent-emoji:cup-with-straw',
  'guarana': 'fluent-emoji:cup-with-straw',
  'cerveja': 'fluent-emoji:beer-mug',
  'vinho': 'fluent-emoji:wine-glass',
  'champagne': 'fluent-emoji:bottle-with-popping-cork',
  'espumante': 'fluent-emoji:bottle-with-popping-cork',
  'água': 'fluent-emoji:potable-water',
  'agua': 'fluent-emoji:potable-water',
  'água mineral': 'fluent-emoji:potable-water',
  'agua mineral': 'fluent-emoji:potable-water',
  'água com gás': 'fluent-emoji:potable-water',
  'agua com gas': 'fluent-emoji:potable-water',
  'energético': 'fluent-emoji:cup-with-straw',
  'energetico': 'fluent-emoji:cup-with-straw',
  'isotônico': 'fluent-emoji:beverage-box',
  'isotonico': 'fluent-emoji:beverage-box',
  'gatorade': 'fluent-emoji:beverage-box',
  'mate': 'fluent-emoji:mate',
  'chimarrão': 'fluent-emoji:mate',
  'chimarrao': 'fluent-emoji:mate',
  'achocolatado': 'fluent-emoji:glass-of-milk',
  'nescau': 'fluent-emoji:glass-of-milk',
  'toddy': 'fluent-emoji:glass-of-milk',

  // Limpeza
  'detergente': 'fluent-emoji:soap',
  'sabão': 'fluent-emoji:soap',
  'sabao': 'fluent-emoji:soap',
  'sabão em pó': 'fluent-emoji:soap',
  'sabao em po': 'fluent-emoji:soap',
  'omo': 'fluent-emoji:soap',
  'desinfetante': 'fluent-emoji:soap',
  'amaciante': 'fluent-emoji:soap',
  'água sanitária': 'fluent-emoji:soap',
  'agua sanitaria': 'fluent-emoji:soap',
  'alvejante': 'fluent-emoji:soap',
  'limpa vidros': 'fluent-emoji:soap',
  'multiuso': 'fluent-emoji:soap',
  'esponja': 'fluent-emoji:sponge',
  'pano': 'fluent-emoji:sponge',
  'vassoura': 'fluent-emoji:bucket',
  'rodo': 'fluent-emoji:bucket',
  'balde': 'fluent-emoji:bucket',
  'saco de lixo': 'fluent-emoji:bucket',

  // Higiene Pessoal
  'sabonete': 'fluent-emoji:soap',
  'shampoo': 'fluent-emoji:soap',
  'condicionador': 'fluent-emoji:soap',
  'desodorante': 'fluent-emoji:soap',
  'pasta de dente': 'fluent-emoji:toothbrush',
  'creme dental': 'fluent-emoji:toothbrush',
  'escova de dente': 'fluent-emoji:toothbrush',
  'fio dental': 'fluent-emoji:toothbrush',
  'papel higiênico': 'fluent-emoji:roll-of-paper',
  'papel higienico': 'fluent-emoji:roll-of-paper',
  'papel toalha': 'fluent-emoji:roll-of-paper',
  'lenço de papel': 'fluent-emoji:roll-of-paper',
  'lenco de papel': 'fluent-emoji:roll-of-paper',
  'absorvente': 'fluent-emoji:roll-of-paper',
  'cotonete': 'fluent-emoji:roll-of-paper',
  'algodão': 'fluent-emoji:roll-of-paper',
  'algodao': 'fluent-emoji:roll-of-paper',
  'hidratante': 'fluent-emoji:soap',
  'protetor solar': 'fluent-emoji:soap',
  'perfume': 'fluent-emoji:soap',
  'colônia': 'fluent-emoji:soap',
  'colonia': 'fluent-emoji:soap',

  // Ovos
  'ovo': 'fluent-emoji:egg',
  'ovos': 'fluent-emoji:egg',
  'ovo branco': 'fluent-emoji:egg',
  'ovo vermelho': 'fluent-emoji:egg',
  'ovo caipira': 'fluent-emoji:egg',

  // Doces e Guloseimas
  'chocolate': 'fluent-emoji:chocolate-bar',
  'bombom': 'fluent-emoji:chocolate-bar',
  'bala': 'fluent-emoji:candy',
  'chiclete': 'fluent-emoji:candy',
  'pirulito': 'fluent-emoji:lollipop',
  'sorvete': 'fluent-emoji:ice-cream',
  'picolé': 'fluent-emoji:ice',
  'picole': 'fluent-emoji:ice',
  'açaí': 'fluent-emoji:ice-cream',
  'acai': 'fluent-emoji:ice-cream',
  'brigadeiro': 'fluent-emoji:chocolate-bar',
  'beijinho': 'fluent-emoji:candy',
  'paçoca': 'fluent-emoji:candy',
  'pacoca': 'fluent-emoji:candy',
  'pé de moleque': 'fluent-emoji:candy',
  'pe de moleque': 'fluent-emoji:candy',

  // Biscoitos e Snacks
  'biscoito': 'fluent-emoji:cookie',
  'bolacha': 'fluent-emoji:cookie',
  'cookie': 'fluent-emoji:cookie',
  'wafer': 'fluent-emoji:cookie',
  'torrada': 'fluent-emoji:bread',
  'salgadinho': 'fluent-emoji:potato-chips',
  'chips': 'fluent-emoji:potato-chips',
  'doritos': 'fluent-emoji:potato-chips',
  'ruffles': 'fluent-emoji:potato-chips',
  'cheetos': 'fluent-emoji:potato-chips',
  'pipoca': 'fluent-emoji:popcorn',
  'amendoim': 'fluent-emoji:peanuts',
  'castanha': 'fluent-emoji:peanuts',
  'nozes': 'fluent-emoji:peanuts',

  // Temperos e Condimentos
  'sal': 'fluent-emoji:salt',
  'açúcar': 'fluent-emoji:salt',
  'acucar': 'fluent-emoji:salt',
  'óleo': 'fluent-emoji:olive-oil',
  'oleo': 'fluent-emoji:olive-oil',
  'azeite': 'fluent-emoji:olive',
  'azeitona': 'fluent-emoji:olive',
  'vinagre': 'fluent-emoji:olive-oil',
  'molho': 'fluent-emoji:olive-oil',
  'catchup': 'fluent-emoji:olive-oil',
  'ketchup': 'fluent-emoji:olive-oil',
  'mostarda': 'fluent-emoji:olive-oil',
  'maionese': 'fluent-emoji:olive-oil',
  'orégano': 'fluent-emoji:leafy-green',
  'oregano': 'fluent-emoji:leafy-green',
  'páprica': 'fluent-emoji:hot-pepper',
  'paprica': 'fluent-emoji:hot-pepper',
  'cominho': 'fluent-emoji:leafy-green',
  'curry': 'fluent-emoji:leafy-green',
  'canela': 'fluent-emoji:leafy-green',
  'cravo': 'fluent-emoji:leafy-green',
  'noz moscada': 'fluent-emoji:leafy-green',
  'colorau': 'fluent-emoji:hot-pepper',
  'colorífico': 'fluent-emoji:hot-pepper',
  'colorifico': 'fluent-emoji:hot-pepper',
  'mel': 'fluent-emoji:honey-pot',
  'geléia': 'fluent-emoji:honey-pot',
  'geleia': 'fluent-emoji:honey-pot',
  'doce de leite': 'fluent-emoji:honey-pot',

  // Congelados
  'pizza': 'fluent-emoji:pizza',
  'hambúrguer': 'fluent-emoji:hamburger',
  'hamburguer': 'fluent-emoji:hamburger',
  'nuggets': 'fluent-emoji:poultry-leg',
  'empanado': 'fluent-emoji:poultry-leg',
  'hot dog': 'fluent-emoji:hot-dog',
  'cachorro quente': 'fluent-emoji:hot-dog',
  'batata congelada': 'fluent-emoji:potato',
  'batata frita': 'fluent-emoji:potato-chips',
  'lasanha congelada': 'fluent-emoji:spaghetti',

  // Comidas Prontas
  'sushi': 'fluent-emoji:sushi',
  'taco': 'fluent-emoji:taco',
  'burrito': 'fluent-emoji:burrito',
  'sanduíche': 'fluent-emoji:sandwich',
  'sanduiche': 'fluent-emoji:sandwich',
  'salada': 'fluent-emoji:green-salad',
  'sopa': 'fluent-emoji:steaming-bowl',
  'ramen': 'fluent-emoji:steaming-bowl',

  // Pet
  'ração': 'fluent-emoji:bowl-with-spoon',
  'racao': 'fluent-emoji:bowl-with-spoon',
  'ração de cachorro': 'fluent-emoji:dog-face',
  'racao de cachorro': 'fluent-emoji:dog-face',
  'ração de gato': 'fluent-emoji:cat-face',
  'racao de gato': 'fluent-emoji:cat-face',
  'petisco': 'fluent-emoji:bone',
  'osso': 'fluent-emoji:bone',
  'areia': 'fluent-emoji:bucket',
  'areia de gato': 'fluent-emoji:cat-face',

  // Bebê
  'fralda': 'fluent-emoji:baby',
  'mamadeira': 'fluent-emoji:baby-bottle',
  'lenço umedecido': 'fluent-emoji:baby',
  'lenco umedecido': 'fluent-emoji:baby',
  'pomada': 'fluent-emoji:baby',

  // Saúde e Farmácia
  'remédio': 'fluent-emoji:pill',
  'remedio': 'fluent-emoji:pill',
  'medicamento': 'fluent-emoji:pill',
  'vitamina': 'fluent-emoji:pill',
  'band-aid': 'fluent-emoji:adhesive-bandage',
  'curativo': 'fluent-emoji:adhesive-bandage',
  'termômetro': 'fluent-emoji:thermometer',
  'termometro': 'fluent-emoji:thermometer',
  'álcool': 'fluent-emoji:soap',
  'alcool': 'fluent-emoji:soap',
  'álcool gel': 'fluent-emoji:soap',
  'alcool gel': 'fluent-emoji:soap',

  // Outros
  'pilha': 'fluent-emoji:battery',
  'bateria': 'fluent-emoji:battery',
  'lâmpada': 'fluent-emoji:light-bulb',
  'lampada': 'fluent-emoji:light-bulb',
  'vela': 'fluent-emoji:candle',
  'fósforo': 'fluent-emoji:fire',
  'fosforo': 'fluent-emoji:fire',
  'isqueiro': 'fluent-emoji:fire',
}

export const DEFAULT_ICON = 'fluent-emoji:shopping-cart'

// Lista de ícones disponíveis para seleção manual (200+ ícones)
export const AVAILABLE_ICONS = [
  // Compras e geral
  { name: 'Carrinho', icon: 'fluent-emoji:shopping-cart', keywords: ['compras', 'mercado', 'supermercado'] },
  { name: 'Sacola', icon: 'fluent-emoji:shopping-bags', keywords: ['compras', 'bag', 'bolsa'] },
  { name: 'Dinheiro', icon: 'fluent-emoji:money-bag', keywords: ['grana', 'money', 'pagar'] },

  // Frutas
  { name: 'Maçã Vermelha', icon: 'fluent-emoji:red-apple', keywords: ['fruta', 'maca', 'apple'] },
  { name: 'Maçã Verde', icon: 'fluent-emoji:green-apple', keywords: ['fruta', 'maca', 'apple'] },
  { name: 'Banana', icon: 'fluent-emoji:banana', keywords: ['fruta'] },
  { name: 'Laranja', icon: 'fluent-emoji:tangerine', keywords: ['fruta', 'citrico', 'citrus'] },
  { name: 'Morango', icon: 'fluent-emoji:strawberry', keywords: ['fruta', 'berry'] },
  { name: 'Uva', icon: 'fluent-emoji:grapes', keywords: ['fruta'] },
  { name: 'Melancia', icon: 'fluent-emoji:watermelon', keywords: ['fruta'] },
  { name: 'Abacaxi', icon: 'fluent-emoji:pineapple', keywords: ['fruta', 'ananás'] },
  { name: 'Limão', icon: 'fluent-emoji:lemon', keywords: ['fruta', 'citrico'] },
  { name: 'Manga', icon: 'fluent-emoji:mango', keywords: ['fruta'] },
  { name: 'Pera', icon: 'fluent-emoji:pear', keywords: ['fruta'] },
  { name: 'Pêssego', icon: 'fluent-emoji:peach', keywords: ['fruta', 'pessego'] },
  { name: 'Cereja', icon: 'fluent-emoji:cherries', keywords: ['fruta', 'cherry'] },
  { name: 'Kiwi', icon: 'fluent-emoji:kiwi-fruit', keywords: ['fruta'] },
  { name: 'Melão', icon: 'fluent-emoji:melon', keywords: ['fruta', 'melao'] },
  { name: 'Coco', icon: 'fluent-emoji:coconut', keywords: ['fruta'] },
  { name: 'Blueberry', icon: 'fluent-emoji:blueberries', keywords: ['fruta', 'berry', 'mirtilo'] },
  { name: 'Abacate', icon: 'fluent-emoji:avocado', keywords: ['fruta', 'avocado'] },
  { name: 'Amora', icon: 'fluent-emoji:blueberries', keywords: ['fruta', 'berry'] },
  { name: 'Framboesa', icon: 'fluent-emoji:strawberry', keywords: ['fruta', 'berry'] },

  // Vegetais e Verduras
  { name: 'Tomate', icon: 'fluent-emoji:tomato', keywords: ['vegetal', 'verdura'] },
  { name: 'Alface', icon: 'fluent-emoji:leafy-green', keywords: ['verdura', 'folha', 'salada'] },
  { name: 'Cenoura', icon: 'fluent-emoji:carrot', keywords: ['vegetal', 'raiz'] },
  { name: 'Batata', icon: 'fluent-emoji:potato', keywords: ['vegetal', 'raiz'] },
  { name: 'Cebola', icon: 'fluent-emoji:onion', keywords: ['vegetal', 'tempero'] },
  { name: 'Alho', icon: 'fluent-emoji:garlic', keywords: ['tempero', 'condimento'] },
  { name: 'Brócolis', icon: 'fluent-emoji:broccoli', keywords: ['vegetal', 'verdura', 'brocolis'] },
  { name: 'Berinjela', icon: 'fluent-emoji:eggplant', keywords: ['vegetal'] },
  { name: 'Pimentão', icon: 'fluent-emoji:bell-pepper', keywords: ['vegetal', 'pimentao'] },
  { name: 'Pepino', icon: 'fluent-emoji:cucumber', keywords: ['vegetal', 'salada'] },
  { name: 'Milho', icon: 'fluent-emoji:ear-of-corn', keywords: ['vegetal', 'cereal'] },
  { name: 'Cogumelo', icon: 'fluent-emoji:mushroom', keywords: ['vegetal', 'funghi'] },
  { name: 'Pimenta', icon: 'fluent-emoji:hot-pepper', keywords: ['tempero', 'picante', 'apimentado'] },
  { name: 'Abóbora', icon: 'fluent-emoji:pumpkin', keywords: ['vegetal', 'abobora'] },
  { name: 'Abobrinha', icon: 'fluent-emoji:cucumber', keywords: ['vegetal'] },
  { name: 'Beterraba', icon: 'fluent-emoji:onion', keywords: ['vegetal', 'raiz'] },
  { name: 'Rabanete', icon: 'fluent-emoji:onion', keywords: ['vegetal', 'raiz'] },
  { name: 'Couve', icon: 'fluent-emoji:leafy-green', keywords: ['verdura', 'vegetal'] },
  { name: 'Espinafre', icon: 'fluent-emoji:leafy-green', keywords: ['verdura', 'vegetal'] },
  { name: 'Repolho', icon: 'fluent-emoji:leafy-green', keywords: ['verdura', 'vegetal'] },
  { name: 'Rúcula', icon: 'fluent-emoji:leafy-green', keywords: ['verdura', 'salada'] },

  // Laticínios
  { name: 'Leite', icon: 'fluent-emoji:glass-of-milk', keywords: ['lacticinio', 'dairy', 'leite'] },
  { name: 'Queijo', icon: 'fluent-emoji:cheese-wedge', keywords: ['lacticinio', 'dairy'] },
  { name: 'Manteiga', icon: 'fluent-emoji:butter', keywords: ['lacticinio', 'dairy'] },

  // Padaria
  { name: 'Pão', icon: 'fluent-emoji:bread', keywords: ['padaria', 'pao', 'bread'] },
  { name: 'Baguete', icon: 'fluent-emoji:baguette-bread', keywords: ['padaria', 'pao', 'frances'] },
  { name: 'Pretzel', icon: 'fluent-emoji:pretzel', keywords: ['padaria', 'pao'] },
  { name: 'Bagel', icon: 'fluent-emoji:bagel', keywords: ['padaria', 'pao'] },
  { name: 'Bolo', icon: 'fluent-emoji:birthday-cake', keywords: ['padaria', 'doce', 'cake'] },
  { name: 'Croissant', icon: 'fluent-emoji:croissant', keywords: ['padaria', 'pao'] },
  { name: 'Donut', icon: 'fluent-emoji:doughnut', keywords: ['doce', 'padaria', 'rosquinha'] },
  { name: 'Cupcake', icon: 'fluent-emoji:cupcake', keywords: ['doce', 'bolo', 'padaria'] },
  { name: 'Torta', icon: 'fluent-emoji:pie', keywords: ['doce', 'padaria', 'sobremesa'] },

  // Carnes e Peixes
  { name: 'Carne', icon: 'fluent-emoji:cut-of-meat', keywords: ['proteina', 'meat'] },
  { name: 'Frango', icon: 'fluent-emoji:poultry-leg', keywords: ['carne', 'proteina', 'chicken'] },
  { name: 'Peixe', icon: 'fluent-emoji:fish', keywords: ['proteina', 'fish'] },
  { name: 'Bacon', icon: 'fluent-emoji:bacon', keywords: ['carne', 'porco'] },
  { name: 'Hot Dog', icon: 'fluent-emoji:hot-dog', keywords: ['salsciha', 'lanche'] },
  { name: 'Camarão', icon: 'fluent-emoji:shrimp', keywords: ['frutos do mar', 'seafood', 'camarao'] },

  // Grãos, Massas e Cereais
  { name: 'Arroz', icon: 'fluent-emoji:cooked-rice', keywords: ['grao', 'cereal'] },
  { name: 'Feijão', icon: 'fluent-emoji:beans', keywords: ['grao', 'legume', 'feijao'] },
  { name: 'Macarrão', icon: 'fluent-emoji:spaghetti', keywords: ['massa', 'pasta', 'macarrao'] },

  // Bebidas
  { name: 'Café', icon: 'fluent-emoji:hot-beverage', keywords: ['bebida', 'coffee', 'cafe'] },
  { name: 'Chá', icon: 'fluent-emoji:teacup-without-handle', keywords: ['bebida', 'tea', 'cha'] },
  { name: 'Suco', icon: 'fluent-emoji:beverage-box', keywords: ['bebida', 'juice'] },
  { name: 'Refrigerante', icon: 'fluent-emoji:cup-with-straw', keywords: ['bebida', 'soda'] },
  { name: 'Cerveja', icon: 'fluent-emoji:beer-mug', keywords: ['bebida', 'alcool', 'beer'] },
  { name: 'Vinho Tinto', icon: 'fluent-emoji:wine-glass', keywords: ['bebida', 'alcool', 'wine'] },
  { name: 'Champagne', icon: 'fluent-emoji:bottle-with-popping-cork', keywords: ['bebida', 'alcool', 'espumante'] },
  { name: 'Água', icon: 'fluent-emoji:potable-water', keywords: ['bebida', 'agua', 'water'] },
  { name: 'Leite Caixinha', icon: 'fluent-emoji:glass-of-milk', keywords: ['bebida', 'leite'] },
  { name: 'Mate', icon: 'fluent-emoji:mate', keywords: ['bebida', 'chimarrao'] },
  { name: 'Energético', icon: 'fluent-emoji:cup-with-straw', keywords: ['bebida', 'energetico', 'energy'] },
  { name: 'Isotônico', icon: 'fluent-emoji:beverage-box', keywords: ['bebida', 'isotonico', 'gatorade'] },
  { name: 'Achocolatado', icon: 'fluent-emoji:glass-of-milk', keywords: ['bebida', 'chocolate', 'nescau'] },

  // Limpeza e Higiene
  { name: 'Sabão', icon: 'fluent-emoji:soap', keywords: ['limpeza', 'higiene', 'sabao'] },
  { name: 'Escova de Dente', icon: 'fluent-emoji:toothbrush', keywords: ['higiene', 'dente'] },
  { name: 'Papel Higiênico', icon: 'fluent-emoji:roll-of-paper', keywords: ['higiene', 'papel', 'banheiro'] },
  { name: 'Esponja', icon: 'fluent-emoji:sponge', keywords: ['limpeza', 'louça', 'louça'] },
  { name: 'Balde', icon: 'fluent-emoji:bucket', keywords: ['limpeza'] },

  // Ovos e Proteínas
  { name: 'Ovo', icon: 'fluent-emoji:egg', keywords: ['proteina', 'egg'] },

  // Doces e Snacks
  { name: 'Chocolate', icon: 'fluent-emoji:chocolate-bar', keywords: ['doce', 'candy'] },
  { name: 'Biscoito', icon: 'fluent-emoji:cookie', keywords: ['doce', 'snack', 'bolacha'] },
  { name: 'Pirulito', icon: 'fluent-emoji:lollipop', keywords: ['doce', 'candy'] },
  { name: 'Bala', icon: 'fluent-emoji:candy', keywords: ['doce'] },
  { name: 'Sorvete', icon: 'fluent-emoji:ice-cream', keywords: ['doce', 'gelado'] },
  { name: 'Picolé', icon: 'fluent-emoji:ice', keywords: ['doce', 'gelado', 'picole'] },
  { name: 'Pipoca', icon: 'fluent-emoji:popcorn', keywords: ['snack', 'cinema'] },
  { name: 'Chips', icon: 'fluent-emoji:potato-chips', keywords: ['snack', 'batata'] },
  { name: 'Pretzel', icon: 'fluent-emoji:pretzel', keywords: ['snack'] },
  { name: 'Amendoim', icon: 'fluent-emoji:peanuts', keywords: ['snack', 'castanha'] },
  { name: 'Castanha', icon: 'fluent-emoji:peanuts', keywords: ['snack', 'nozes'] },
  { name: 'Açaí', icon: 'fluent-emoji:ice-cream', keywords: ['doce', 'acai', 'sobremesa'] },
  { name: 'Brigadeiro', icon: 'fluent-emoji:chocolate-bar', keywords: ['doce', 'festa'] },
  { name: 'Paçoca', icon: 'fluent-emoji:candy', keywords: ['doce', 'pacoca', 'amendoim'] },

  // Temperos e Condimentos
  { name: 'Sal', icon: 'fluent-emoji:salt', keywords: ['tempero', 'condimento'] },
  { name: 'Açúcar', icon: 'fluent-emoji:salt', keywords: ['tempero', 'acucar', 'doce'] },
  { name: 'Azeite', icon: 'fluent-emoji:olive-oil', keywords: ['oleo', 'oil', 'tempero'] },
  { name: 'Óleo', icon: 'fluent-emoji:olive-oil', keywords: ['oleo', 'cozinha'] },
  { name: 'Azeitona', icon: 'fluent-emoji:olive', keywords: ['tempero'] },
  { name: 'Mel', icon: 'fluent-emoji:honey-pot', keywords: ['doce', 'tempero'] },
  { name: 'Geleia', icon: 'fluent-emoji:honey-pot', keywords: ['doce', 'geleia'] },
  { name: 'Ketchup', icon: 'fluent-emoji:olive-oil', keywords: ['molho', 'catchup'] },
  { name: 'Mostarda', icon: 'fluent-emoji:olive-oil', keywords: ['molho', 'condimento'] },
  { name: 'Maionese', icon: 'fluent-emoji:olive-oil', keywords: ['molho', 'condimento'] },
  { name: 'Pimenta', icon: 'fluent-emoji:hot-pepper', keywords: ['tempero', 'picante'] },

  // Congelados
  { name: 'Pizza', icon: 'fluent-emoji:pizza', keywords: ['comida', 'congelado', 'fast food'] },
  { name: 'Hambúrguer', icon: 'fluent-emoji:hamburger', keywords: ['comida', 'fast food', 'hamburguer'] },
  { name: 'Taco', icon: 'fluent-emoji:taco', keywords: ['comida', 'mexicano'] },
  { name: 'Burrito', icon: 'fluent-emoji:burrito', keywords: ['comida', 'mexicano'] },
  { name: 'Sushi', icon: 'fluent-emoji:sushi', keywords: ['comida', 'japones', 'peixe'] },
  { name: 'Ramen', icon: 'fluent-emoji:steaming-bowl', keywords: ['comida', 'macarrao', 'sopa'] },

  // Outros alimentos
  { name: 'Sanduíche', icon: 'fluent-emoji:sandwich', keywords: ['lanche', 'sanduiche'] },
  { name: 'Burrito', icon: 'fluent-emoji:burrito', keywords: ['comida'] },
  { name: 'Taco', icon: 'fluent-emoji:taco', keywords: ['comida'] },
  { name: 'Salada', icon: 'fluent-emoji:green-salad', keywords: ['vegetal', 'verdura', 'saudavel'] },
  { name: 'Sopa', icon: 'fluent-emoji:steaming-bowl', keywords: ['comida', 'quente'] },
  { name: 'Petisco', icon: 'fluent-emoji:popcorn', keywords: ['snack', 'aperitivo'] },

  // Utensílios e Casa
  { name: 'Garfo e Faca', icon: 'fluent-emoji:fork-and-knife', keywords: ['utensilio', 'cozinha'] },
  { name: 'Colher', icon: 'fluent-emoji:spoon', keywords: ['utensilio', 'cozinha'] },
  { name: 'Copo', icon: 'fluent-emoji:tumbler-glass', keywords: ['cozinha', 'bebida'] },
  { name: 'Garrafa', icon: 'fluent-emoji:bottle-with-popping-cork', keywords: ['bebida'] },
  { name: 'Pote', icon: 'fluent-emoji:jar', keywords: ['cozinha', 'armazenamento'] },
  { name: 'Caixa', icon: 'fluent-emoji:package', keywords: ['armazenamento', 'embalagem'] },

  // Pet
  { name: 'Cachorro', icon: 'fluent-emoji:dog-face', keywords: ['pet', 'animal', 'cao'] },
  { name: 'Gato', icon: 'fluent-emoji:cat-face', keywords: ['pet', 'animal'] },
  { name: 'Osso', icon: 'fluent-emoji:bone', keywords: ['pet', 'cachorro'] },
  { name: 'Ração', icon: 'fluent-emoji:bowl-with-spoon', keywords: ['pet', 'comida', 'racao'] },

  // Plantas
  { name: 'Planta', icon: 'fluent-emoji:potted-plant', keywords: ['planta', 'vaso', 'jardim'] },
  { name: 'Flor', icon: 'fluent-emoji:blossom', keywords: ['planta', 'jardim'] },
  { name: 'Rosa', icon: 'fluent-emoji:rose', keywords: ['flor', 'planta'] },
  { name: 'Tulipa', icon: 'fluent-emoji:tulip', keywords: ['flor', 'planta'] },

  // Bebê
  { name: 'Mamadeira', icon: 'fluent-emoji:baby-bottle', keywords: ['bebe', 'baby'] },
  { name: 'Fralda', icon: 'fluent-emoji:baby', keywords: ['bebe', 'baby'] },

  // Saúde
  { name: 'Remédio', icon: 'fluent-emoji:pill', keywords: ['saude', 'medicamento', 'remedio'] },
  { name: 'Seringa', icon: 'fluent-emoji:syringe', keywords: ['saude', 'medico'] },
  { name: 'Band-Aid', icon: 'fluent-emoji:adhesive-bandage', keywords: ['saude', 'curativo'] },

  // Diversos
  { name: 'Livro', icon: 'fluent-emoji:books', keywords: ['leitura', 'estudo'] },
  { name: 'Lápis', icon: 'fluent-emoji:pencil', keywords: ['escrita', 'estudo', 'lapis'] },
  { name: 'Tesoura', icon: 'fluent-emoji:scissors', keywords: ['cortar', 'utensilio'] },
  { name: 'Chave', icon: 'fluent-emoji:key', keywords: ['casa'] },
  { name: 'Presente', icon: 'fluent-emoji:wrapped-gift', keywords: ['gift', 'presente'] },
  { name: 'Balão', icon: 'fluent-emoji:balloon', keywords: ['festa', 'balao'] },
  { name: 'Vela', icon: 'fluent-emoji:candle', keywords: ['decoracao', 'luz'] },
  { name: 'Lâmpada', icon: 'fluent-emoji:light-bulb', keywords: ['luz', 'lampada', 'eletrico'] },
  { name: 'Pilha', icon: 'fluent-emoji:battery', keywords: ['eletrico', 'energia'] },
  { name: 'Fogo', icon: 'fluent-emoji:fire', keywords: ['fogo', 'fosforo', 'isqueiro'] },
  { name: 'Termômetro', icon: 'fluent-emoji:thermometer', keywords: ['saude', 'temperatura'] },
  { name: 'Pote/Jar', icon: 'fluent-emoji:jar', keywords: ['cozinha', 'pote', 'vidro'] },
  { name: 'Caixa/Pacote', icon: 'fluent-emoji:package', keywords: ['caixa', 'embalagem', 'entrega'] },
  { name: 'Guarda-chuva', icon: 'fluent-emoji:umbrella', keywords: ['chuva', 'guarda-chuva'] },
  { name: 'Óculos', icon: 'fluent-emoji:glasses', keywords: ['oculos', 'visao'] },
  { name: 'Relógio', icon: 'fluent-emoji:watch', keywords: ['relogio', 'tempo', 'hora'] },

  // Ferramentas e Construção
  { name: 'Martelo', icon: 'fluent-emoji:hammer', keywords: ['ferramenta', 'construcao', 'tool', 'hammer'] },
  { name: 'Chave Inglesa', icon: 'fluent-emoji:wrench', keywords: ['ferramenta', 'tool', 'wrench', 'chave'] },
  { name: 'Parafuso', icon: 'fluent-emoji:nut-and-bolt', keywords: ['ferramenta', 'parafuso', 'bolt'] },
  { name: 'Serra', icon: 'fluent-emoji:carpentry-saw', keywords: ['ferramenta', 'madeira', 'saw', 'serra'] },
  { name: 'Machado', icon: 'fluent-emoji:axe', keywords: ['ferramenta', 'madeira', 'axe', 'machado'] },
  { name: 'Pá', icon: 'fluent-emoji:pick', keywords: ['ferramenta', 'jardim', 'shovel', 'pa'] },
  { name: 'Alicate', icon: 'fluent-emoji:clamp', keywords: ['ferramenta', 'tool', 'pliers'] },
  { name: 'Fita Métrica', icon: 'fluent-emoji:straight-ruler', keywords: ['medida', 'ruler', 'regua'] },
  { name: 'Escada', icon: 'fluent-emoji:ladder', keywords: ['construcao', 'ladder', 'escada'] },
  { name: 'Corrente', icon: 'fluent-emoji:chains', keywords: ['corrente', 'chain', 'ferro'] },
  { name: 'Ímã', icon: 'fluent-emoji:magnet', keywords: ['ima', 'magnet', 'magnetico'] },
  { name: 'Engrenagem', icon: 'fluent-emoji:gear', keywords: ['mecanica', 'gear', 'engrenagem'] },
  { name: 'Âncora', icon: 'fluent-emoji:anchor', keywords: ['ancora', 'anchor', 'peso'] },

  // Casa e Móveis
  { name: 'Casa', icon: 'fluent-emoji:house', keywords: ['casa', 'home', 'moradia'] },
  { name: 'Cama', icon: 'fluent-emoji:bed', keywords: ['cama', 'bed', 'dormir'] },
  { name: 'Sofá', icon: 'fluent-emoji:couch-and-lamp', keywords: ['sofa', 'couch', 'movel'] },
  { name: 'Cadeira', icon: 'fluent-emoji:chair', keywords: ['cadeira', 'chair', 'movel'] },
  { name: 'Porta', icon: 'fluent-emoji:door', keywords: ['porta', 'door', 'entrada'] },
  { name: 'Janela', icon: 'fluent-emoji:window', keywords: ['janela', 'window', 'vidro'] },
  { name: 'Banheira', icon: 'fluent-emoji:bathtub', keywords: ['banheira', 'bath', 'banheiro'] },
  { name: 'Chuveiro', icon: 'fluent-emoji:shower', keywords: ['chuveiro', 'shower', 'banho'] },
  { name: 'Vaso Sanitário', icon: 'fluent-emoji:toilet', keywords: ['vaso', 'toilet', 'banheiro'] },
  { name: 'Torneira', icon: 'fluent-emoji:potable-water', keywords: ['torneira', 'agua', 'faucet'] },
  { name: 'Extintor', icon: 'fluent-emoji:fire-extinguisher', keywords: ['extintor', 'fogo', 'seguranca'] },
  { name: 'Alarme', icon: 'fluent-emoji:bell', keywords: ['alarme', 'bell', 'sino'] },
  { name: 'Cadeado', icon: 'fluent-emoji:locked', keywords: ['cadeado', 'lock', 'seguranca'] },
  { name: 'Desbloqueado', icon: 'fluent-emoji:unlocked', keywords: ['aberto', 'unlock', 'desbloqueado'] },

  // Eletrônicos e Tecnologia
  { name: 'Celular', icon: 'fluent-emoji:mobile-phone', keywords: ['celular', 'phone', 'smartphone'] },
  { name: 'Computador', icon: 'fluent-emoji:laptop', keywords: ['computador', 'laptop', 'notebook'] },
  { name: 'Desktop', icon: 'fluent-emoji:desktop-computer', keywords: ['desktop', 'computer', 'pc'] },
  { name: 'Teclado', icon: 'fluent-emoji:keyboard', keywords: ['teclado', 'keyboard', 'digitar'] },
  { name: 'Mouse', icon: 'fluent-emoji:computer-mouse', keywords: ['mouse', 'rato', 'computador'] },
  { name: 'Impressora', icon: 'fluent-emoji:printer', keywords: ['impressora', 'printer', 'imprimir'] },
  { name: 'TV', icon: 'fluent-emoji:television', keywords: ['tv', 'televisao', 'television'] },
  { name: 'Rádio', icon: 'fluent-emoji:radio', keywords: ['radio', 'som', 'musica'] },
  { name: 'Câmera', icon: 'fluent-emoji:camera', keywords: ['camera', 'foto', 'photography'] },
  { name: 'Filmadora', icon: 'fluent-emoji:video-camera', keywords: ['filmadora', 'video', 'camera'] },
  { name: 'Fone', icon: 'fluent-emoji:headphone', keywords: ['fone', 'headphone', 'audio'] },
  { name: 'Microfone', icon: 'fluent-emoji:microphone', keywords: ['microfone', 'mic', 'audio'] },
  { name: 'CD/DVD', icon: 'fluent-emoji:optical-disk', keywords: ['cd', 'dvd', 'disco'] },
  { name: 'Disquete', icon: 'fluent-emoji:floppy-disk', keywords: ['disquete', 'floppy', 'salvar'] },
  { name: 'USB', icon: 'fluent-emoji:floppy-disk', keywords: ['usb', 'pendrive', 'memoria'] },
  { name: 'Joystick', icon: 'fluent-emoji:video-game', keywords: ['joystick', 'game', 'controle'] },

  // Vestuário e Acessórios
  { name: 'Camiseta', icon: 'fluent-emoji:t-shirt', keywords: ['camiseta', 'shirt', 'roupa'] },
  { name: 'Jeans', icon: 'fluent-emoji:jeans', keywords: ['calca', 'jeans', 'pants'] },
  { name: 'Vestido', icon: 'fluent-emoji:dress', keywords: ['vestido', 'dress', 'roupa'] },
  { name: 'Gravata', icon: 'fluent-emoji:necktie', keywords: ['gravata', 'tie', 'gravata'] },
  { name: 'Kimono', icon: 'fluent-emoji:kimono', keywords: ['kimono', 'japones', 'roupa'] },
  { name: 'Sapato', icon: 'fluent-emoji:running-shoe', keywords: ['sapato', 'shoe', 'tenis'] },
  { name: 'Sandália', icon: 'fluent-emoji:thong-sandal', keywords: ['sandalia', 'sandal', 'chinelo'] },
  { name: 'Bota', icon: 'fluent-emoji:hiking-boot', keywords: ['bota', 'boot', 'sapato'] },
  { name: 'Meia', icon: 'fluent-emoji:socks', keywords: ['meia', 'sock', 'pe'] },
  { name: 'Luva', icon: 'fluent-emoji:gloves', keywords: ['luva', 'glove', 'mao'] },
  { name: 'Chapéu', icon: 'fluent-emoji:billed-cap', keywords: ['chapeu', 'cap', 'bone'] },
  { name: 'Coroa', icon: 'fluent-emoji:crown', keywords: ['coroa', 'crown', 'rei'] },
  { name: 'Mochila', icon: 'fluent-emoji:backpack', keywords: ['mochila', 'backpack', 'bag'] },
  { name: 'Bolsa', icon: 'fluent-emoji:handbag', keywords: ['bolsa', 'bag', 'purse'] },
  { name: 'Carteira', icon: 'fluent-emoji:purse', keywords: ['carteira', 'wallet', 'dinheiro'] },
  { name: 'Maleta', icon: 'fluent-emoji:briefcase', keywords: ['maleta', 'briefcase', 'trabalho'] },

  // Esportes e Atividades
  { name: 'Bola Futebol', icon: 'fluent-emoji:soccer-ball', keywords: ['bola', 'futebol', 'soccer'] },
  { name: 'Bola Basquete', icon: 'fluent-emoji:basketball', keywords: ['bola', 'basquete', 'basketball'] },
  { name: 'Bola Vôlei', icon: 'fluent-emoji:volleyball', keywords: ['bola', 'volei', 'volleyball'] },
  { name: 'Bola Tênis', icon: 'fluent-emoji:tennis', keywords: ['tenis', 'tennis', 'raquete'] },
  { name: 'Bola Beisebol', icon: 'fluent-emoji:baseball', keywords: ['baseball', 'beisebol', 'bola'] },
  { name: 'Raquete', icon: 'fluent-emoji:badminton', keywords: ['raquete', 'badminton', 'esporte'] },
  { name: 'Piscina', icon: 'fluent-emoji:water-wave', keywords: ['piscina', 'pool', 'nadar'] },
  { name: 'Surf', icon: 'fluent-emoji:surfing', keywords: ['surf', 'prancha', 'surfing'] },
  { name: 'Ski', icon: 'fluent-emoji:skier', keywords: ['ski', 'neve', 'skiing'] },
  { name: 'Patins', icon: 'fluent-emoji:roller-skate', keywords: ['patins', 'skate', 'roller'] },
  { name: 'Dardo', icon: 'fluent-emoji:direct-hit', keywords: ['dardo', 'dart', 'alvo'] },
  { name: 'Troféu', icon: 'fluent-emoji:trophy', keywords: ['trofeu', 'trophy', 'premio'] },
  { name: 'Medalha', icon: 'fluent-emoji:1st-place-medal', keywords: ['medalha', 'medal', 'primeiro'] },
  { name: 'Haltere', icon: 'fluent-emoji:person-lifting-weights', keywords: ['haltere', 'gym', 'musculacao'] },

  // Transporte e Veículos
  { name: 'Carro', icon: 'fluent-emoji:automobile', keywords: ['carro', 'car', 'veiculo'] },
  { name: 'Ônibus', icon: 'fluent-emoji:bus', keywords: ['onibus', 'bus', 'transporte'] },
  { name: 'Caminhão', icon: 'fluent-emoji:delivery-truck', keywords: ['caminhao', 'truck', 'entrega'] },
  { name: 'Trator', icon: 'fluent-emoji:tractor', keywords: ['trator', 'tractor', 'fazenda'] },
  { name: 'Bicicleta', icon: 'fluent-emoji:bicycle', keywords: ['bicicleta', 'bike', 'pedalar'] },
  { name: 'Moto', icon: 'fluent-emoji:motorcycle', keywords: ['moto', 'motorcycle', 'motocicleta'] },
  { name: 'Trem', icon: 'fluent-emoji:locomotive', keywords: ['trem', 'train', 'trilho'] },
  { name: 'Avião', icon: 'fluent-emoji:airplane', keywords: ['aviao', 'plane', 'voar'] },
  { name: 'Helicóptero', icon: 'fluent-emoji:helicopter', keywords: ['helicoptero', 'helicopter', 'voar'] },
  { name: 'Foguete', icon: 'fluent-emoji:rocket', keywords: ['foguete', 'rocket', 'espaco'] },
  { name: 'Barco', icon: 'fluent-emoji:sailboat', keywords: ['barco', 'boat', 'vela'] },
  { name: 'Navio', icon: 'fluent-emoji:ship', keywords: ['navio', 'ship', 'barco'] },
  { name: 'Âncora', icon: 'fluent-emoji:anchor', keywords: ['ancora', 'anchor', 'barco'] },
  { name: 'Combustível', icon: 'fluent-emoji:fuel-pump', keywords: ['combustivel', 'fuel', 'gasolina', 'posto'] },
  { name: 'Semáforo', icon: 'fluent-emoji:vertical-traffic-light', keywords: ['semaforo', 'traffic', 'sinal'] },
  { name: 'Placa STOP', icon: 'fluent-emoji:stop-sign', keywords: ['stop', 'pare', 'placa'] },

  // Natureza e Meio Ambiente
  { name: 'Árvore', icon: 'fluent-emoji:deciduous-tree', keywords: ['arvore', 'tree', 'natureza'] },
  { name: 'Pinheiro', icon: 'fluent-emoji:evergreen-tree', keywords: ['pinheiro', 'pine', 'arvore'] },
  { name: 'Palmeira', icon: 'fluent-emoji:palm-tree', keywords: ['palmeira', 'palm', 'coqueiro'] },
  { name: 'Cacto', icon: 'fluent-emoji:cactus', keywords: ['cacto', 'cactus', 'deserto'] },
  { name: 'Folha', icon: 'fluent-emoji:fallen-leaf', keywords: ['folha', 'leaf', 'natureza'] },
  { name: 'Trevo', icon: 'fluent-emoji:four-leaf-clover', keywords: ['trevo', 'clover', 'sorte'] },
  { name: 'Girassol', icon: 'fluent-emoji:sunflower', keywords: ['girassol', 'sunflower', 'flor'] },
  { name: 'Hibisco', icon: 'fluent-emoji:hibiscus', keywords: ['hibisco', 'hibiscus', 'flor'] },
  { name: 'Sol', icon: 'fluent-emoji:sun', keywords: ['sol', 'sun', 'dia'] },
  { name: 'Lua', icon: 'fluent-emoji:crescent-moon', keywords: ['lua', 'moon', 'noite'] },
  { name: 'Estrela', icon: 'fluent-emoji:star', keywords: ['estrela', 'star', 'ceu'] },
  { name: 'Nuvem', icon: 'fluent-emoji:cloud', keywords: ['nuvem', 'cloud', 'ceu'] },
  { name: 'Raio', icon: 'fluent-emoji:high-voltage', keywords: ['raio', 'lightning', 'eletrico'] },
  { name: 'Chuva', icon: 'fluent-emoji:cloud-with-rain', keywords: ['chuva', 'rain', 'tempo'] },
  { name: 'Neve', icon: 'fluent-emoji:snowflake', keywords: ['neve', 'snow', 'frio'] },
  { name: 'Arco-íris', icon: 'fluent-emoji:rainbow', keywords: ['arco-iris', 'rainbow', 'cores'] },
  { name: 'Fogo', icon: 'fluent-emoji:fire', keywords: ['fogo', 'fire', 'chama'] },
  { name: 'Gota', icon: 'fluent-emoji:droplet', keywords: ['gota', 'drop', 'agua'] },
  { name: 'Montanha', icon: 'fluent-emoji:mountain', keywords: ['montanha', 'mountain', 'natureza'] },
  { name: 'Vulcão', icon: 'fluent-emoji:volcano', keywords: ['vulcao', 'volcano', 'lava'] },
  { name: 'Praia', icon: 'fluent-emoji:beach-with-umbrella', keywords: ['praia', 'beach', 'areia'] },
  { name: 'Terra', icon: 'fluent-emoji:globe-showing-americas', keywords: ['terra', 'earth', 'mundo', 'planeta'] },

  // Animais
  { name: 'Leão', icon: 'fluent-emoji:lion', keywords: ['leao', 'lion', 'animal'] },
  { name: 'Tigre', icon: 'fluent-emoji:tiger-face', keywords: ['tigre', 'tiger', 'animal'] },
  { name: 'Urso', icon: 'fluent-emoji:bear', keywords: ['urso', 'bear', 'animal'] },
  { name: 'Panda', icon: 'fluent-emoji:panda', keywords: ['panda', 'urso', 'animal'] },
  { name: 'Coelho', icon: 'fluent-emoji:rabbit-face', keywords: ['coelho', 'rabbit', 'animal'] },
  { name: 'Rato', icon: 'fluent-emoji:mouse-face', keywords: ['rato', 'mouse', 'roedor'] },
  { name: 'Esquilo', icon: 'fluent-emoji:chipmunk', keywords: ['esquilo', 'squirrel', 'animal'] },
  { name: 'Macaco', icon: 'fluent-emoji:monkey-face', keywords: ['macaco', 'monkey', 'animal'] },
  { name: 'Elefante', icon: 'fluent-emoji:elephant', keywords: ['elefante', 'elephant', 'animal'] },
  { name: 'Girafa', icon: 'fluent-emoji:giraffe', keywords: ['girafa', 'giraffe', 'animal'] },
  { name: 'Zebra', icon: 'fluent-emoji:zebra', keywords: ['zebra', 'animal', 'listras'] },
  { name: 'Cavalo', icon: 'fluent-emoji:horse-face', keywords: ['cavalo', 'horse', 'animal'] },
  { name: 'Vaca', icon: 'fluent-emoji:cow-face', keywords: ['vaca', 'cow', 'animal'] },
  { name: 'Porco', icon: 'fluent-emoji:pig-face', keywords: ['porco', 'pig', 'animal'] },
  { name: 'Ovelha', icon: 'fluent-emoji:ewe', keywords: ['ovelha', 'sheep', 'animal'] },
  { name: 'Galinha', icon: 'fluent-emoji:chicken', keywords: ['galinha', 'chicken', 'ave'] },
  { name: 'Pássaro', icon: 'fluent-emoji:bird', keywords: ['passaro', 'bird', 'ave'] },
  { name: 'Pinguim', icon: 'fluent-emoji:penguin', keywords: ['pinguim', 'penguin', 'ave'] },
  { name: 'Coruja', icon: 'fluent-emoji:owl', keywords: ['coruja', 'owl', 'ave'] },
  { name: 'Pato', icon: 'fluent-emoji:duck', keywords: ['pato', 'duck', 'ave'] },
  { name: 'Sapo', icon: 'fluent-emoji:frog', keywords: ['sapo', 'frog', 'anfibio'] },
  { name: 'Cobra', icon: 'fluent-emoji:snake', keywords: ['cobra', 'snake', 'reptil'] },
  { name: 'Tartaruga', icon: 'fluent-emoji:turtle', keywords: ['tartaruga', 'turtle', 'reptil'] },
  { name: 'Borboleta', icon: 'fluent-emoji:butterfly', keywords: ['borboleta', 'butterfly', 'inseto'] },
  { name: 'Abelha', icon: 'fluent-emoji:honeybee', keywords: ['abelha', 'bee', 'inseto'] },
  { name: 'Joaninha', icon: 'fluent-emoji:lady-beetle', keywords: ['joaninha', 'ladybug', 'inseto'] },
  { name: 'Aranha', icon: 'fluent-emoji:spider', keywords: ['aranha', 'spider', 'inseto'] },
  { name: 'Caracol', icon: 'fluent-emoji:snail', keywords: ['caracol', 'snail', 'lento'] },
  { name: 'Polvo', icon: 'fluent-emoji:octopus', keywords: ['polvo', 'octopus', 'mar'] },
  { name: 'Caranguejo', icon: 'fluent-emoji:crab', keywords: ['caranguejo', 'crab', 'mar'] },
  { name: 'Baleia', icon: 'fluent-emoji:whale', keywords: ['baleia', 'whale', 'mar'] },
  { name: 'Golfinho', icon: 'fluent-emoji:dolphin', keywords: ['golfinho', 'dolphin', 'mar'] },
  { name: 'Tubarão', icon: 'fluent-emoji:shark', keywords: ['tubarao', 'shark', 'mar'] },

  // Escritório e Papelaria
  { name: 'Envelope', icon: 'fluent-emoji:envelope', keywords: ['envelope', 'carta', 'correio'] },
  { name: 'Carta', icon: 'fluent-emoji:love-letter', keywords: ['carta', 'letter', 'mensagem'] },
  { name: 'Clipboard', icon: 'fluent-emoji:clipboard', keywords: ['clipboard', 'prancheta', 'papel'] },
  { name: 'Pasta', icon: 'fluent-emoji:file-folder', keywords: ['pasta', 'folder', 'arquivo'] },
  { name: 'Calendário', icon: 'fluent-emoji:calendar', keywords: ['calendario', 'calendar', 'data'] },
  { name: 'Pushpin', icon: 'fluent-emoji:pushpin', keywords: ['pushpin', 'alfinete', 'fixar'] },
  { name: 'Clipe', icon: 'fluent-emoji:paperclip', keywords: ['clipe', 'clip', 'papel'] },
  { name: 'Caneta', icon: 'fluent-emoji:pen', keywords: ['caneta', 'pen', 'escrever'] },
  { name: 'Marcador', icon: 'fluent-emoji:crayon', keywords: ['marcador', 'crayon', 'colorir'] },
  { name: 'Pincel', icon: 'fluent-emoji:paintbrush', keywords: ['pincel', 'brush', 'pintar'] },
  { name: 'Paleta', icon: 'fluent-emoji:artist-palette', keywords: ['paleta', 'palette', 'cores', 'tinta'] },
  { name: 'Lupa', icon: 'fluent-emoji:magnifying-glass-tilted-left', keywords: ['lupa', 'magnifying', 'buscar'] },
  { name: 'Grampeador', icon: 'fluent-emoji:closed-book', keywords: ['grampeador', 'stapler', 'escritorio'] },

  // Símbolos e Sinalizações
  { name: 'Check Verde', icon: 'fluent-emoji:check-mark-button', keywords: ['check', 'ok', 'correto', 'verde'] },
  { name: 'X Vermelho', icon: 'fluent-emoji:cross-mark', keywords: ['x', 'errado', 'nao', 'vermelho'] },
  { name: 'Interrogação', icon: 'fluent-emoji:question-mark', keywords: ['interrogacao', 'question', 'duvida'] },
  { name: 'Exclamação', icon: 'fluent-emoji:exclamation-mark', keywords: ['exclamacao', 'exclamation', 'alerta'] },
  { name: 'Proibido', icon: 'fluent-emoji:prohibited', keywords: ['proibido', 'prohibited', 'nao'] },
  { name: 'Reciclagem', icon: 'fluent-emoji:recycling-symbol', keywords: ['reciclagem', 'recycle', 'meio-ambiente'] },
  { name: 'Seta Direita', icon: 'fluent-emoji:right-arrow', keywords: ['seta', 'arrow', 'direita'] },
  { name: 'Seta Esquerda', icon: 'fluent-emoji:left-arrow', keywords: ['seta', 'arrow', 'esquerda'] },
  { name: 'Seta Cima', icon: 'fluent-emoji:up-arrow', keywords: ['seta', 'arrow', 'cima'] },
  { name: 'Seta Baixo', icon: 'fluent-emoji:down-arrow', keywords: ['seta', 'arrow', 'baixo'] },
  { name: 'Coração', icon: 'fluent-emoji:red-heart', keywords: ['coracao', 'heart', 'amor'] },
  { name: 'Coração Partido', icon: 'fluent-emoji:broken-heart', keywords: ['coracao', 'broken', 'triste'] },
  { name: 'Estrela Dourada', icon: 'fluent-emoji:glowing-star', keywords: ['estrela', 'star', 'dourada'] },
  { name: 'Diamante', icon: 'fluent-emoji:gem-stone', keywords: ['diamante', 'diamond', 'joia'] },
  { name: 'Moeda', icon: 'fluent-emoji:coin', keywords: ['moeda', 'coin', 'dinheiro'] },
  { name: 'Bandeira', icon: 'fluent-emoji:triangular-flag', keywords: ['bandeira', 'flag', 'sinal'] },
  { name: 'Sino', icon: 'fluent-emoji:bell', keywords: ['sino', 'bell', 'notificacao'] },
  { name: 'Megafone', icon: 'fluent-emoji:megaphone', keywords: ['megafone', 'megaphone', 'anuncio'] },
  { name: 'Telefone', icon: 'fluent-emoji:telephone', keywords: ['telefone', 'phone', 'ligar'] },
  { name: 'Email', icon: 'fluent-emoji:e-mail', keywords: ['email', 'mail', 'correio'] },

  // Comida Internacional e Especiais
  { name: 'Croissant', icon: 'fluent-emoji:croissant', keywords: ['croissant', 'pao', 'frances'] },
  { name: 'Pretzel', icon: 'fluent-emoji:pretzel', keywords: ['pretzel', 'alemao', 'pao'] },
  { name: 'Dumpling', icon: 'fluent-emoji:dumpling', keywords: ['dumpling', 'gyoza', 'chines'] },
  { name: 'Fortune Cookie', icon: 'fluent-emoji:fortune-cookie', keywords: ['fortune', 'cookie', 'chines', 'sorte'] },
  { name: 'Chopsticks', icon: 'fluent-emoji:chopsticks', keywords: ['chopsticks', 'hashi', 'chines'] },
  { name: 'Waffle', icon: 'fluent-emoji:waffle', keywords: ['waffle', 'breakfast', 'cafe'] },
  { name: 'Falafel', icon: 'fluent-emoji:falafel', keywords: ['falafel', 'arabe', 'comida'] },
  { name: 'Tamale', icon: 'fluent-emoji:tamale', keywords: ['tamale', 'mexicano', 'comida'] },

  // Celebração e Festas
  { name: 'Confete', icon: 'fluent-emoji:confetti-ball', keywords: ['confete', 'confetti', 'festa'] },
  { name: 'Fogos', icon: 'fluent-emoji:fireworks', keywords: ['fogos', 'fireworks', 'festa'] },
  { name: 'Champanhe', icon: 'fluent-emoji:bottle-with-popping-cork', keywords: ['champagne', 'festa', 'celebracao'] },
  { name: 'Festa', icon: 'fluent-emoji:party-popper', keywords: ['festa', 'party', 'celebracao'] },
  { name: 'Bolo Aniversário', icon: 'fluent-emoji:birthday-cake', keywords: ['bolo', 'aniversario', 'birthday'] },
]

export function getProductIcon(nome: string, categoria?: string): string {
  const nomeLower = nome.toLowerCase()

  for (const [key, icon] of Object.entries(PRODUCT_ICONS)) {
    if (nomeLower.includes(key)) {
      return icon
    }
  }

  if (categoria) {
    const categoriaLower = categoria.toLowerCase()
    for (const [key, icon] of Object.entries(PRODUCT_ICONS)) {
      if (categoriaLower.includes(key)) {
        return icon
      }
    }
  }

  return DEFAULT_ICON
}

export const CATEGORIAS: Record<string, string[]> = {
  'Laticínios': ['leite', 'iogurte', 'queijo', 'manteiga', 'requeijão', 'cream cheese', 'nata', 'coalhada'],
  'Padaria': ['pão', 'pao', 'torrada', 'bolo', 'croissant', 'bisnaga', 'sonho', 'rosca'],
  'Carnes e Peixes': ['carne', 'frango', 'peixe', 'bacon', 'salsicha', 'linguiça', 'linguica', 'file', 'filé', 'costela', 'picanha'],
  'Frutas': ['maçã', 'maca', 'banana', 'laranja', 'uva', 'morango', 'melancia', 'abacaxi', 'limão', 'limao', 'manga', 'pera', 'pêssego', 'pessego', 'kiwi', 'melão', 'melao', 'mamão', 'mamao'],
  'Vegetais e Verduras': ['tomate', 'alface', 'cenoura', 'batata', 'cebola', 'alho', 'brócolis', 'brocolis', 'berinjela', 'pimentão', 'pimentao', 'pepino', 'couve', 'espinafre', 'repolho'],
  'Grãos e Massas': ['arroz', 'feijão', 'feijao', 'macarrão', 'macarrao', 'espaguete', 'lentilha', 'grão de bico', 'grao', 'farinha'],
  'Bebidas': ['café', 'cafe', 'chá', 'cha', 'suco', 'refrigerante', 'cerveja', 'vinho', 'água', 'agua', 'energético', 'energetico', 'isotônico', 'isotonico'],
  'Limpeza': ['detergente', 'sabão', 'sabao', 'desinfetante', 'amaciante', 'água sanitária', 'agua sanitaria', 'esponja', 'pano', 'alvejante'],
  'Higiene Pessoal': ['pasta de dente', 'escova de dente', 'sabonete', 'shampoo', 'condicionador', 'desodorante', 'papel higiênico', 'papel higienico', 'fio dental'],
  'Doces e Guloseimas': ['chocolate', 'bala', 'chiclete', 'sorvete', 'bombom', 'pirulito', 'brigadeiro', 'paçoca', 'pacoca', 'doce'],
  'Congelados': ['sorvete', 'pizza congelada', 'lasanha congelada', 'hambúrguer', 'hamburguer', 'nuggets', 'batata congelada'],
  'Temperos e Condimentos': ['sal', 'açúcar', 'acucar', 'óleo', 'oleo', 'azeite', 'vinagre', 'pimenta', 'orégano', 'oregano', 'cominho'],
  'Ovos': ['ovo', 'ovos'],
  'Biscoitos e Snacks': ['biscoito', 'bolacha', 'salgadinho', 'chips'],
}

export const ORDEM_CATEGORIAS = [
  'Frutas',
  'Vegetais e Verduras',
  'Laticínios',
  'Carnes e Peixes',
  'Ovos',
  'Padaria',
  'Grãos e Massas',
  'Doces e Guloseimas',
  'Biscoitos e Snacks',
  'Bebidas',
  'Congelados',
  'Temperos e Condimentos',
  'Limpeza',
  'Higiene Pessoal',
  'Outros'
]

export function getCategoriaFromNome(nome: string): string {
  const nomeLower = nome.toLowerCase()

  for (const [categoria, palavras] of Object.entries(CATEGORIAS)) {
    if (palavras.some(palavra => nomeLower.includes(palavra))) {
      return categoria
    }
  }

  return 'Outros'
}
